import { useState, useEffect } from 'react';
import { useAccount } from 'wagmi';

export function useQuests() {
  const { address, isConnected } = useAccount();
  const [quests, setQuests] = useState([]);
  const [loading, setLoading] = useState(true);

  // No demo quests - will be generated by Kwala automation
  const questTemplates = [];

  useEffect(() => {
    if (isConnected && address) {
      // No demo data - quests will come from Kwala automation
      setQuests([]);
      setLoading(false);
    } else {
      setQuests([]);
      setLoading(false);
    }
  }, [isConnected, address]);

  const completeQuest = (questId) => {
    setQuests(prev => prev.map(quest => 
      quest.id === questId 
        ? { ...quest, status: 'completed', progress: quest.target }
        : quest
    ));
  };

  const updateQuestProgress = (questId, progress) => {
    setQuests(prev => prev.map(quest => 
      quest.id === questId 
        ? { 
            ...quest, 
            progress: Math.min(progress, quest.target),
            status: progress >= quest.target ? 'completed' : 'active'
          }
        : quest
    ));
  };

  return {
    quests,
    loading,
    completeQuest,
    updateQuestProgress,
    refetch: () => {}
  };
}