name: "ChainQuest Quest Automation"
description: "Automated quest generation and completion tracking"
version: "1.0.0"

triggers:
  - name: "daily_quest_reset"
    type: "schedule"
    cron: "0 0 * * *"
    
  - name: "character_minted"
    type: "contract_event"
    contract: "0x0aF5DACFe9DeAAf38413D55CeC0F16a850ED162D"
    event: "Transfer"
    chain: "polygon-amoy"
    filter:
      from: "0x0000000000000000000000000000000000000000"

actions:
  - name: "generate_daily_quests"
    type: "webhook"
    url: "https://chainquest-backend.vercel.app/api/quests/generate"
    method: "POST"
    headers:
      Content-Type: "application/json"
    conditions:
      - trigger: "daily_quest_reset"
      
  - name: "reward_character_mint"
    type: "webhook"
    url: "https://chainquest-backend.vercel.app/webhooks/quest-completed"
    method: "POST"
    headers:
      Content-Type: "application/json"
    body:
      player: "{{trigger.to}}"
      questId: "mint_character"
      rewards:
        tokens: 500
        xp: 250
    conditions:
      - trigger: "character_minted"

notifications:
  - name: "quest_completed_notification"
    type: "webhook"
    url: "https://chainquest-backend.vercel.app/webhooks/quest-completed"
    conditions:
      - action: "reward_character_mint"