# ChainQuest - Automated Quest System
# This workflow monitors player activities and automatically manages quests

name: "Quest Automation System"
description: "Monitors on-chain activities and manages quest completion automatically"

triggers:
  # Monitor NFT transfers to detect character acquisitions
  - name: "character_acquired"
    type: "contract_event"
    contract: "0x0aF5DACFe9DeAAf38413D55CeC0F16a850ED162D" # ChainQuest Character NFT contract on Amoy
    event: "Transfer"
    chains: ["polygon-amoy"]
    
  # Monitor quest contract interactions
  - name: "quest_interaction"
    type: "contract_event" 
    contract: "0x..." # Quest Manager contract (to be deployed)
    event: "QuestStarted"
    chains: ["polygon-amoy"]
    
  # Time-based quest generation
  - name: "daily_quest_reset"
    type: "schedule"
    cron: "0 0 * * *" # Daily at midnight UTC

actions:
  # Generate personalized quests based on player history
  - name: "generate_daily_quests"
    type: "contract_call"
    contract: "0x..." # Quest Manager contract
    function: "generateDailyQuests"
    conditions:
      - trigger: "daily_quest_reset"
    parameters:
      - name: "playerAddress"
        value: "{{trigger.player}}"
      - name: "difficulty"
        value: "{{player.level}}"
        
  # Automatically reward quest completion
  - name: "reward_quest_completion"
    type: "contract_call"
    contract: "0x..." # Reward Manager contract  
    function: "distributeRewards"
    conditions:
      - trigger: "quest_interaction"
      - event_data.questStatus: "completed"
    parameters:
      - name: "player"
        value: "{{trigger.player}}"
      - name: "questId" 
        value: "{{trigger.questId}}"
      - name: "rewardType"
        value: "{{quest.rewardType}}"
        
  # Cross-chain quest synchronization
  - name: "sync_quest_progress"
    type: "cross_chain_call"
    source_chain: "{{trigger.chain}}"
    target_chains: ["ethereum", "polygon", "bsc", "arbitrum"]
    contract: "0x..." # Quest Sync contract
    function: "syncQuestProgress"
    conditions:
      - trigger: "quest_interaction"
    parameters:
      - name: "player"
        value: "{{trigger.player}}"
      - name: "questId"
        value: "{{trigger.questId}}"
      - name: "progress"
        value: "{{trigger.progress}}"

# Notification system for quest updates
notifications:
  - name: "quest_completed"
    type: "webhook"
    url: "https://chainquest-api.vercel.app/webhooks/quest-completed"
    conditions:
      - action: "reward_quest_completion"
    payload:
      player: "{{trigger.player}}"
      questId: "{{trigger.questId}}"
      rewards: "{{action.rewards}}"
      
  - name: "new_quest_available"
    type: "webhook" 
    url: "https://chainquest-api.vercel.app/webhooks/new-quest"
    conditions:
      - action: "generate_daily_quests"
    payload:
      player: "{{trigger.player}}"
      quests: "{{action.generatedQuests}}"